sudo: required

services:
  -docker
  
language: python

before_install:
- docker pull laszewski/cloudmesh-tex:0.0.1
- docker run laszewski/cloudmesh-tex:0.0.1 /bin/sh -c "cd /book; git pull"

script:
  - export HOME=/
  - export PYENV_ROOT=/.pyenv
  - export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
  - python --version
  - cd /book; git pull
  - cd /book; make travis

#deploy:
#  provider: releases
#  api_key:
#    secure: [YOUR KEY]
#  file:
#  - _build/your_file_1.pdf
#  - _build/your_file_2.pdf
#  skip_cleanup: true
#  on:
#    tags: true