sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends 

python:
  - "3.6"
  
addons:
  apt:
    packages:
      - texlive-full
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-fonts-extra
      - dvipng
      - texlive-latex-recommended
      - latexmk
 #     - wget
 #     - curl
 #     - sed
 #     - grep

install:
  - python --version
  - sudo pip install pathlib
  - sudo pip install -r requirements.txt
  
script:
  - python --version
  - make travis

#deploy:
#  provider: releases
#  api_key:
#    secure: [YOUR KEY]
#  file:
#  - _build/your_file_1.pdf
#  - _build/your_file_2.pdf
#  skip_cleanup: true
#  on:
#    tags: true